"""Regenerate BOOKS_LIST.md and every category README.md from the PDFs in the repo.

Run from the repo root after adding or removing books:
    python3 scripts/generate_catalog.py
"""
import os
import subprocess
from collections import defaultdict
from datetime import date
from urllib.parse import quote

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Short description for each top-level folder.
DESCRIPTIONS = {
    "AI Books": "LLMs, AI agents, RAG, LangChain, LLMOps, generative AI and deep learning.",
    "AWS & AI From Mammoth": "AWS certification prep, DynamoDB, and ML / generative AI on AWS.",
    "Algorithms": "Algorithms and data structures, from CLRS to interview-style practice.",
    "Apache Kafka": "Kafka fundamentals, Kafka Streams, ksqlDB, and tuning and benchmarking.",
    "App Development": "App development with Flutter and agentic coding with Claude Code.",
    "C, C++, C#, and .NET": "Modern C#, .NET and ASP.NET Core.",
    "Cybersecurity": "Cloud security and identity and access management.",
    "Data Visualization": "Dashboards, visual analytics and data-driven decisions.",
    "Databases": "MySQL, PostgreSQL, Redis, Elasticsearch, MongoDB, Cassandra and data modeling.",
    "Development Practices": "Engineering practices: Software Engineering at Google, modern software engineering, regex.",
    "Distributed Systems": "Distributed systems fundamentals, transactions and cloud-native microservices.",
    "Head First": "The Head First series: Java, Go, JavaScript, design patterns, Agile and PMP.",
    "Interview Pattern Book": "Coding interview patterns.",
    "Linux": "Linux kernel, system programming, debuggers, network automation and Git.",
    "Machine Learning": "Machine learning system design.",
    "Non-Technical": "Business, leadership and marketing.",
    "Operating Systems": "Operating system concepts, UNIX internals and how Linux works.",
    "Problem Solving": "The Pragmatic Programmer, system design interviews and engineering effectiveness.",
    "Python & Data": "Python from beginner to advanced, data wrangling, Polars and practical projects.",
    "Raspberry Pi": "Raspberry Pi hardware and projects.",
    "Rust Programming": "Rust design patterns and best practices.",
    "Soft Skills": "Negotiation and personal strengths.",
    "Software Architecture": "Clean Architecture, DDD, microservices, event-driven and enterprise patterns.",
    "Software Architecture & Systems": "Cloud-native design patterns and .NET architecture.",
    "Software Engineering": "Refactoring, TDD, design patterns, debugging and project management classics.",
    "Software Testing": "Unit testing, JUnit, Mockito and load testing with k6.",
    "System Design": "Microservices patterns and REST API design.",
    "devops": "CI/CD, Docker, Kubernetes and DevOps culture.",
    "networking": "Computer networking, network automation, MQTT and Kubernetes networking.",
    "programming": "Java, Spring Boot, Python, concurrency, clean code, design patterns and Git.",
    "security": "Web application and API security.",
}


def title_of(filename):
    return filename[: -len(".pdf")].replace("_", " ").strip()


def anchor(text):
    slug = text.lower().replace(" ", "-")
    return "".join(c for c in slug if c.isalnum() or c in "-_")


def book_lines(entries, base=""):
    lines = []
    for sub, name, path in sorted(entries, key=lambda e: (e[0].lower(), e[1].lower())):
        prefix = f"`{sub}` · " if sub else ""
        rel = path[len(base):] if base and path.startswith(base) else path
        lines.append(f"- {prefix}[{title_of(name)}]({quote(rel)})")
    return lines


def main():
    files = subprocess.run(
        ["git", "-c", "core.quotepath=off", "ls-files", "*.pdf"],
        cwd=REPO, capture_output=True, text=True, check=True,
    ).stdout.splitlines()

    groups = defaultdict(list)
    for f in files:
        parts = f.split("/")
        top = parts[0] if len(parts) > 1 else "General"
        groups[top].append(("/".join(parts[1:-1]), parts[-1], f))

    order = sorted(groups, key=lambda k: (k == "General", k.lower()))

    # BOOKS_LIST.md
    out = [
        "# 📖 Complete Book Catalog", "",
        f"All **{len(files)}** books in this collection, grouped by folder. Click a title to open the PDF.", "",
        "> Generated by `scripts/generate_catalog.py`. Run it again after adding or removing books.", "",
        "## Contents", "",
    ]
    out += [f"- [{k}](#{anchor(k)}) ({len(groups[k])})" for k in order]
    out.append("")
    for k in order:
        out += [f"## {k}", ""] + book_lines(groups[k]) + [""]
    with open(os.path.join(REPO, "BOOKS_LIST.md"), "w", encoding="utf-8") as fh:
        fh.write("\n".join(out))

    # One README.md per category folder
    today = date.today().strftime("%B %Y")
    for k in order:
        if k == "General":
            continue
        n = len(groups[k])
        lines = [
            f"# {k}", "",
            DESCRIPTIONS.get(k, ""), "",
            f"**{n} book{'s' if n != 1 else ''}** in this folder.", "",
            "## Books", "",
        ]
        lines += book_lines(groups[k], base=k + "/")
        lines += ["", "---", "",
                  f"[← Back to all categories](../README.md) · [Full catalog](../BOOKS_LIST.md) · *Updated {today}*", ""]
        with open(os.path.join(REPO, k, "README.md"), "w", encoding="utf-8") as fh:
            fh.write("\n".join(lines))

    print(f"{len(files)} books, {len(order)} groups")


if __name__ == "__main__":
    main()
